redux, redux-saga were added
dmytrocherepakhin/marvel-superheroes pull request #3
Opened 2021-09-22 00:49 UTC by dmytrocherepakhin

2021-09-24 14:15 UTC, alinalaktionova requested changes

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> -        this.state = {
you don't need to move whole state to redux, only data that you gets from api and loading state

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +    fetchComicsSaga(page: string | string[] | null, heroId: number, currentComicsPage: number): IFetchComicsSaga
too many types for page param

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +    hideLoader(): ILoader,
loader methods should be in react

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +export type IComicsPops = {
interface consists of field related to different entities, please split it by sense

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +import { fetchComics, fetchComicsHero, fetchComicsSaga, hideLoader, IFetchComics, IFetchComicsHero, IFetchComicsSaga, ILoader, ISetComicsCurrentPage, setComicsCurrentPage, showLoader } from "../../st
long string, eslint should show error or at least warning in this case

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +        setComicsCurrentPage: (currentComicsPage: number) => dispatch(setComicsCurrentPage(currentComicsPage)),
should be handled by react

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +        const currentComicsPage = this.props.currentComicsPage;
you can use destructuring to get props value and not to write this.props... all the time

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +        const currentComicsPage = this.props.currentComicsPage;
currentPage also better to leave in state

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/HomePage/HomePage.tsx
> +import { fetchHeroes, fetchHeroesSaga, hideLoader, IFetchHeroes, IFetchHeroesSaga, ILoader, ISetHeroesCurrentPage, ISetHeroesNameStartWith, ISetHeroesOrderBy, setHeroesCurrentPage, setHeroesNameStart
the same about linter

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/HomePage/HomePage.tsx
> +import { store } from "../../index";
also see that some strings are double quote  and others are single. Add appropriate eslint rule to handle this

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/HomePage/HomePage.tsx
> +    fetchHeroesSaga(orderBy: string, currentHeroesPage: number, query: string | string[] | null, sort: string | string[] | null, page: string | string[] | null): IFetchHeroesSaga
parameters shouldn't have so many union types

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/HomePage/HomePage.tsx
> +    setHeroesOrderBy(orderBy: string): ISetHeroesOrderBy,
all the same about this interface, no need to pass all methods and state to redux. There is no sense in moving setHeroesNameStartWith, setHeroesOrderBy, setHeroesCurrentPage and so on

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/HomePage/HomePage.tsx
> +        if (this.props.location !== prevProps.location || this.props.currentHeroesPage !== prevProps.currentHeroesPage) { this.makeRequest(); }
code stye...

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/components/api.tsx
> +    page: string | string[] | null): Promise<AxiosResponse> {
same problem with types

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/store/actionTypes/types.tsx
> +export const SET_HEROES_NAME_START_WITH = 'SET_HEROES_NAME_START_WITH'
You should have only 3 actions for each backend request. For example, GET_HERO_REQUEST, GET_HERO_SUCCESS, GET_HERO_ERROR. Rewrite all these actions

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/store/reducers/comicsReducer.tsx
> +        case FETCH_COMICS_SAGA:
unusefull case

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/store/reducers/heroesReducer.tsx
> +        case FETCH_HEROES_SAGA:
same unuseful

2021-09-24 14:15 UTC, alinalaktionova commented on marvel_superheroes/src/store/sagas/comicsSaga.tsx
> +        yield put(hideLoader())
should add errorAction in catch block

2021-09-24 20:17 UTC, dmytrocherepakhin commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +    fetchComicsSaga(page: string | string[] | null, heroId: number, currentComicsPage: number): IFetchComicsSaga
the page param was received as 'queryString.parse(this.props.location.search).page'  with only type 'string | string[] | null'  ??

2021-09-30 10:38 UTC, alinalaktionova requested changes

2021-09-30 10:38 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +    this.setState({ currentComicsPage: currentComicsPage })
you can write just this.setState({ currentComicsPage }), it's the same

2021-09-30 10:38 UTC, alinalaktionova commented on marvel_superheroes/src/components/ComicsPage/ComicsPage.tsx
> +    heroName: state.comicsReducer.heroName,
can use destructuring for this

2021-09-30 10:38 UTC, alinalaktionova commented on marvel_superheroes/src/components/Hero/Hero.tsx
> +import "./Hero.css"
better to use single quote and semicolon in the end of statements. change eslint rules

2021-09-30 10:38 UTC, alinalaktionova commented on marvel_superheroes/src/components/HomePage/HomePage.tsx
> +    const sort = queryStringParse.sort?.toString()
use descructuring

2021-09-30 10:38 UTC, alinalaktionova commented on marvel_superheroes/src/components/api.tsx
> +    orderBy: orderBy,
again you don't need to duplicate property if name is the same

2021-09-30 16:07 UTC, alinalaktionova approved these changes

2021-09-30 16:10 UTC, merged